apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
spec:
  description: >-
    This task runs `oc` commands using the OpenShift CLI.
  params:
    - name: SCRIPT
      type: string
      description: The oc commands to run
    - name: VERSION
      type: string
      default: "latest"
  workspaces:
    - name: source
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -xe
        $(params.SCRIPT)