apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2025-05-20T06:11:16Z'
  generation: 2
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2025-05-20T06:15:26Z'
  name: ci-cd-pipeline
  namespace: sn-labs-dinughit
  resourceVersion: '2181146833'
  uid: f6e2a19c-ba84-411d-94b4-83970dfc3804
spec:
  params:
    - default: counter-app
      name: app-name
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/sn-labs-dinughit/counter-app:latest'
      name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        kind: Task
        name: cleanup
      workspaces:
        - name: source
          workspace: output
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/deenoc/ci-cd-final-project'
        - name: deleteExisting
          value: 'true'
      runAfter:
        - cleanup
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: output
    - name: lint
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: flake8
      workspaces:
        - name: source
          workspace: output
    - name: test
      runAfter:
        - lint
      taskRef:
        kind: Task
        name: nose
      workspaces:
        - name: source
          workspace: output
    - name: build
      params:
        - name: IMAGE
          value: $(params.build-image)
      runAfter:
        - test
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: output
    - name: deploy
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
        - name: VERSION
          value: latest
      runAfter:
        - build
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: source
          workspace: output
  workspaces:
    - name: output
